name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@main

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          
      - name: Install dependencies
        run: "npm ci"

      - name: Build from source
        run: "npm run build"

      - name: Copy artifacts to server
        uses: easingthemes/ssh-deploy@v4.1.10
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: "~/chronology"
          SCRIPT_AFTER: "pm2 reload chronology"
